language: bash
sudo: required
env:
  global:
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=OriHoch/budgetkey-k8s
    - DOCKER_IMAGE=orihoch/open-budget-nginx-frontend
    - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=nginx
    - DEPLOY_VALUES_IMAGE_PROP=image
    - DEPLOY_COMMIT_MESSAGE="automatic update of open-budget-nginx-frontend"
    - DEPLOY_GIT_EMAIL=budgetkey-deployer@null.void
    - DEPLOY_GIT_USER=budgetkey-deployer
services:
  - docker
script:
  - bash .travis.sh script
deploy:
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: changes-for-k8s-environment
